---
- name: Update web servers
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
            name: "Umesh"
            key_name: "naveen"
            region: us-east-1
            instance_type: t2.micro
            security_group: default
            network:
               assign_public_ip: true
            image_id: ami-0557a15b87f6559cf
            tags:
               Environment: Testing

