---
- hosts: localhost
  vars:
      region: "us-east-1"
      instance_type: "t2.micro"
      ami: "ami-0557a15b87f6559cf"
      keypair: "naveen"      
  tasks:
  - ec2:
     key_name: "{{keypair}}"
     image: "{{ami}}"
     region: "{{region}}"
     instance_type: "{{instance_type}}"     
     wait: yes     
     count_tag:
            Name: rambabu
     instance_tags:
              Name: rambabu
    register: ec2
